# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _bilateralfilter
else:
    import _bilateralfilter

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bilateralfilter.delete_SwigPyIterator

    def value(self):
        return _bilateralfilter.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _bilateralfilter.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _bilateralfilter.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _bilateralfilter.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _bilateralfilter.SwigPyIterator_equal(self, x)

    def copy(self):
        return _bilateralfilter.SwigPyIterator_copy(self)

    def next(self):
        return _bilateralfilter.SwigPyIterator_next(self)

    def __next__(self):
        return _bilateralfilter.SwigPyIterator___next__(self)

    def previous(self):
        return _bilateralfilter.SwigPyIterator_previous(self)

    def advance(self, n):
        return _bilateralfilter.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _bilateralfilter.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _bilateralfilter.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _bilateralfilter.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _bilateralfilter.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _bilateralfilter.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _bilateralfilter.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _bilateralfilter:
_bilateralfilter.SwigPyIterator_swigregister(SwigPyIterator)

class FloatVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _bilateralfilter.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _bilateralfilter.FloatVector___nonzero__(self)

    def __bool__(self):
        return _bilateralfilter.FloatVector___bool__(self)

    def __len__(self):
        return _bilateralfilter.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _bilateralfilter.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _bilateralfilter.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _bilateralfilter.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _bilateralfilter.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _bilateralfilter.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _bilateralfilter.FloatVector___setitem__(self, *args)

    def pop(self):
        return _bilateralfilter.FloatVector_pop(self)

    def append(self, x):
        return _bilateralfilter.FloatVector_append(self, x)

    def empty(self):
        return _bilateralfilter.FloatVector_empty(self)

    def size(self):
        return _bilateralfilter.FloatVector_size(self)

    def swap(self, v):
        return _bilateralfilter.FloatVector_swap(self, v)

    def begin(self):
        return _bilateralfilter.FloatVector_begin(self)

    def end(self):
        return _bilateralfilter.FloatVector_end(self)

    def rbegin(self):
        return _bilateralfilter.FloatVector_rbegin(self)

    def rend(self):
        return _bilateralfilter.FloatVector_rend(self)

    def clear(self):
        return _bilateralfilter.FloatVector_clear(self)

    def get_allocator(self):
        return _bilateralfilter.FloatVector_get_allocator(self)

    def pop_back(self):
        return _bilateralfilter.FloatVector_pop_back(self)

    def erase(self, *args):
        return _bilateralfilter.FloatVector_erase(self, *args)

    def __init__(self, *args):
        _bilateralfilter.FloatVector_swiginit(self, _bilateralfilter.new_FloatVector(*args))

    def push_back(self, x):
        return _bilateralfilter.FloatVector_push_back(self, x)

    def front(self):
        return _bilateralfilter.FloatVector_front(self)

    def back(self):
        return _bilateralfilter.FloatVector_back(self)

    def assign(self, n, x):
        return _bilateralfilter.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _bilateralfilter.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _bilateralfilter.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _bilateralfilter.FloatVector_reserve(self, n)

    def capacity(self):
        return _bilateralfilter.FloatVector_capacity(self)
    __swig_destroy__ = _bilateralfilter.delete_FloatVector

# Register FloatVector in _bilateralfilter:
_bilateralfilter.FloatVector_swigregister(FloatVector)


def initializePermutohedral(image, H, W, sigmargb, sigmaxy, lattice_):
    return _bilateralfilter.initializePermutohedral(image, H, W, sigmargb, sigmaxy, lattice_)

def bilateralfilter(image, _in, out, H, W, sigmargb, sigmaxy):
    return _bilateralfilter.bilateralfilter(image, _in, out, H, W, sigmargb, sigmaxy)

def bilateralfilter_batch(images, ins, outs, N, K, H, W, sigmargb, sigmaxy):
    return _bilateralfilter.bilateralfilter_batch(images, ins, outs, N, K, H, W, sigmargb, sigmaxy)
class Permutohedral(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bilateralfilter.Permutohedral_swiginit(self, _bilateralfilter.new_Permutohedral())
    __swig_destroy__ = _bilateralfilter.delete_Permutohedral

    def init(self, feature, feature_size, N):
        return _bilateralfilter.Permutohedral_init(self, feature, feature_size, N)

    def compute(self, *args):
        return _bilateralfilter.Permutohedral_compute(self, *args)

# Register Permutohedral in _bilateralfilter:
_bilateralfilter.Permutohedral_swigregister(Permutohedral)



